In [5]:
import pandas as pd
from pathlib import Path

In [6]:
ruta = Path("../data/raw/Coffee Shop Sales.xlsx")
df = pd.read_excel(ruta)
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [7]:
df.shape

(149116, 11)

In [8]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[us]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
dtypes: datetime64[us](1), float64(1), int64(4), object(1), str(4)
memory usage: 19.8+ MB

¿Cuántas columnas aparecen? 
11 columnas 
¿Qué tipo de dato tiene transaction_date? 
datetime64[us] 
¿Qué tipo de dato tiene transaction_time? 
object 
¿Qué tipo de dato tienen transaction_qty y unit_price? 
int64, float64 
¿Hay columnas que tengan menos valores que el total de filas? 
no 
Si las hay, ¿qué podría significar eso? 
pues representarian algunos valores nulos que tocaria corregir

In [10]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [11]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='str')

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.isna().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [14]:
df.describe()

,transaction_id,transaction_date,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2023-04-15 11:50:32.173609,1.438276,5.342063,47.918607,3.382219
min,1.000000,2023-01-01 00:00:00,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,2023-03-06 00:00:00,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,2023-04-24 00:00:00,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2023-05-30 00:00:00,2.000000,8.000000,60.000000,3.750000
max,149456.000000,2023-06-30 00:00:00,8.000000,8.000000,87.000000,45.000000
std,43153.600016,NaN,0.542509,2.074241,17.930020,2.658723

In [15]:
df[df["unit_price"] == 45].head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
5182,5212,2023-01-10,09:20:43,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
5874,5904,2023-01-11,11:24:31,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
5939,5969,2023-01-11,13:53:09,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
7616,7646,2023-01-14,10:57:38,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
8443,8473,2023-01-15,18:18:51,1,3,Astoria,8,45.0,Coffee beans,Premium Beans,Civet Cat

In [16]:
df.loc[
    df["unit_price"] == 45, ["product_id", "product_type", "product_detail"]
].head()

      product_id   product_type product_detail
5182           8  Premium Beans      Civet Cat
5874           8  Premium Beans      Civet Cat
5939           8  Premium Beans      Civet Cat
7616           8  Premium Beans      Civet Cat
8443           8  Premium Beans      Civet Cat

In [17]:
total_filas = (df["unit_price"] == 45).sum()
total_filas

np.int64(190)

In [29]:
ingreso_total_generado = (((df["unit_price"] == 45) * df["transaction_qty"]) * 45).sum()
ingreso_total_generado

np.int64(11700)

In [30]:
df_new = df.copy()

In [31]:
#13
df_new["revenue"] = df_new["unit_price"] * df_new["transaction_qty"]
df_new["revenue"]

0         6.00
1         6.20
2         9.00
3         2.00
4         6.20
          ...
149111    5.00
149112    6.00
149113    3.00
149114    3.75
149115    1.60
Name: revenue, Length: 149116, dtype: float64

In [32]:
#14
df_new["revenue"].sum()

np.float64(698812.3300000001)

In [35]:
df_new.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail',
       'revenue'],
      dtype='str')

In [70]:
#15
df_new[df_new["unit_price"] == df_new["unit_price"].max()][
    ["product_type", "product_detail", "unit_price"]
]

         product_type product_detail  unit_price
5182    Premium Beans      Civet Cat        45.0
5874    Premium Beans      Civet Cat        45.0
5939    Premium Beans      Civet Cat        45.0
7616    Premium Beans      Civet Cat        45.0
8443    Premium Beans      Civet Cat        45.0
...               ...            ...         ...
144743  Premium Beans      Civet Cat        45.0
145411  Premium Beans      Civet Cat        45.0
148573  Premium Beans      Civet Cat        45.0
148702  Premium Beans      Civet Cat        45.0
148784  Premium Beans      Civet Cat        45.0

[190 rows x 3 columns]

In [63]:
#16
df_new.groupby('product_type')['transaction_qty'].sum().sort_values(ascending=False)

product_type
Brewed Chai tea          26250
Gourmet brewed coffee    25973
Barista Espresso         24943
Brewed Black tea         17462
Hot chocolate            17457
Brewed herbal tea        17328
Organic brewed coffee    13012
Drip coffee              12891
Premium brewed coffee    12431
Scone                    10465
Brewed Green tea          8697
Regular syrup             7606
Pastry                    6961
Biscotti                  5788
Sugar free syrup          2905
Housewares                 555
Chai tea                   443
Organic Beans              420
Premium Beans              406
Gourmet Beans              366
Espresso Beans             319
Herbal tea                 305
Black tea                  303
Drinking Chocolate         266
Clothing                   221
Organic Chocolate          221
House blend Beans          183
Green tea                  159
Green beans                134
Name: transaction_qty, dtype: int64

In [71]:
# Ver la lista completa ordenada de mayor a menor ingreso
#17
top_ingresos = df_new.groupby("product_type")["revenue"].sum().sort_values(ascending=False)
print(top_ingresos.head(1))

product_type
Barista Espresso    91406.2
Name: revenue, dtype: float64

In [74]:
# 18 que categoria aporta mas dinero?
top_ingresos_categoria = df_new.groupby("product_category")["revenue"].sum().sort_values(ascending=False)
top_ingresos_categoria.head(1)

product_category
Coffee    269952.45
Name: revenue, dtype: float64

In [84]:
# 19 tienda que genera mas ingresos
top_ingresos_tienda = df_new.groupby("store_location")["revenue"].sum().sort_values(ascending=False)
top_ingresos_tienda.head(1)

store_location
Hell's Kitchen    236511.17
Name: revenue, dtype: float64

In [83]:
df_new["store_location"].unique()

<ArrowStringArray>
['Lower Manhattan', 'Hell's Kitchen', 'Astoria']
Length: 3, dtype: str

In [89]:
df_new["transaction_date"]

0        2023-01-01
1        2023-01-01
2        2023-01-01
3        2023-01-01
4        2023-01-01
            ...
149111   2023-06-30
149112   2023-06-30
149113   2023-06-30
149114   2023-06-30
149115   2023-06-30
Name: transaction_date, Length: 149116, dtype: datetime64[us]

In [95]:
# 20 Día de la semana con mayores ingresos
df_new["day_of_week"] = df_new["transaction_date"].dt.day_name()
top_dias_ingresos = df_new.groupby("day_of_week")["revenue"].sum().sort_values(ascending=False)
top_dias_ingresos.head(1)

day_of_week
Monday    101677.28
Name: revenue, dtype: float64

In [109]:
# 21  a que hora se genera mas dinero
df_new["transaction_time"] = pd.to_datetime(df_new["transaction_time"], format="%H:%M:%S")
df_new["hour_of_day"] = df_new["transaction_time"].dt.hour

top_horas_ventas = df_new.groupby("hour_of_day")["revenue"].sum().sort_values(ascending=False)
top_horas_ventas.head(1)

hour_of_day
10    88673.39
Name: revenue, dtype: float64

In [100]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[us]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
 11  revenue           149116 non-null  float64
 12  day_of_week       149116 non-null  str
dtypes: datetime64[us](1), float64(2), int64(4), object(1), str(5)
memory usage: 23.1+ MB

In [114]:
# 22 en promedio por transaccion cuanto se vende
df_new["transaction_qty"].mean()

np.float64(1.438276241315486)