In [1]:
import pandas as pd
from pathlib import Path

In [2]:
ruta = Path("../data/raw/Coffee Shop Sales.xlsx")
df = pd.read_excel(ruta)
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [3]:
df.shape

(149116, 11)

In [4]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[us]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
dtypes: datetime64[us](1), float64(1), int64(4), object(1), str(4)
memory usage: 19.8+ MB

¿Cuántas columnas aparecen? 
11 columnas 
¿Qué tipo de dato tiene transaction_date? 
datetime64[us] 
¿Qué tipo de dato tiene transaction_time? 
object 
¿Qué tipo de dato tienen transaction_qty y unit_price? 
int64, float64 
¿Hay columnas que tengan menos valores que el total de filas? 
no 
Si las hay, ¿qué podría significar eso? 
pues representarian algunos valores nulos que tocaria corregir

In [6]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [7]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='str')

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isna().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [10]:
df.describe()

,transaction_id,transaction_date,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2023-04-15 11:50:32.173609,1.438276,5.342063,47.918607,3.382219
min,1.000000,2023-01-01 00:00:00,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,2023-03-06 00:00:00,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,2023-04-24 00:00:00,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2023-05-30 00:00:00,2.000000,8.000000,60.000000,3.750000
max,149456.000000,2023-06-30 00:00:00,8.000000,8.000000,87.000000,45.000000
std,43153.600016,NaN,0.542509,2.074241,17.930020,2.658723

In [11]:
df[df["unit_price"] == 45].head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
5182,5212,2023-01-10,09:20:43,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
5874,5904,2023-01-11,11:24:31,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
5939,5969,2023-01-11,13:53:09,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
7616,7646,2023-01-14,10:57:38,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
8443,8473,2023-01-15,18:18:51,1,3,Astoria,8,45.0,Coffee beans,Premium Beans,Civet Cat

In [12]:
df.loc[
    df["unit_price"] == 45, ["product_id", "product_type", "product_detail"]
].head()

      product_id   product_type product_detail
5182           8  Premium Beans      Civet Cat
5874           8  Premium Beans      Civet Cat
5939           8  Premium Beans      Civet Cat
7616           8  Premium Beans      Civet Cat
8443           8  Premium Beans      Civet Cat

In [13]:
total_filas = (df["unit_price"] == 45).sum()
total_filas

np.int64(190)

In [14]:
ingreso_total_generado = (((df["unit_price"] == 45) * df["transaction_qty"]) * 45).sum()
ingreso_total_generado

np.int64(11700)

In [15]:
df_new = df.copy()

In [16]:
#13
df_new["revenue"] = df_new["unit_price"] * df_new["transaction_qty"]
df_new["revenue"]

0         6.00
1         6.20
2         9.00
3         2.00
4         6.20
          ...
149111    5.00
149112    6.00
149113    3.00
149114    3.75
149115    1.60
Name: revenue, Length: 149116, dtype: float64

In [17]:
#14
df_new["revenue"].sum()

np.float64(698812.3300000001)

In [18]:
df_new.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail',
       'revenue'],
      dtype='str')

In [19]:
#15
df_new[df_new["unit_price"] == df_new["unit_price"].max()][
    ["product_type", "product_detail", "unit_price"]
]

         product_type product_detail  unit_price
5182    Premium Beans      Civet Cat        45.0
5874    Premium Beans      Civet Cat        45.0
5939    Premium Beans      Civet Cat        45.0
7616    Premium Beans      Civet Cat        45.0
8443    Premium Beans      Civet Cat        45.0
...               ...            ...         ...
144743  Premium Beans      Civet Cat        45.0
145411  Premium Beans      Civet Cat        45.0
148573  Premium Beans      Civet Cat        45.0
148702  Premium Beans      Civet Cat        45.0
148784  Premium Beans      Civet Cat        45.0

[190 rows x 3 columns]

In [20]:
#16
df_new.groupby('product_type')['transaction_qty'].sum().sort_values(ascending=False)

product_type
Brewed Chai tea          26250
Gourmet brewed coffee    25973
Barista Espresso         24943
Brewed Black tea         17462
Hot chocolate            17457
Brewed herbal tea        17328
Organic brewed coffee    13012
Drip coffee              12891
Premium brewed coffee    12431
Scone                    10465
Brewed Green tea          8697
Regular syrup             7606
Pastry                    6961
Biscotti                  5788
Sugar free syrup          2905
Housewares                 555
Chai tea                   443
Organic Beans              420
Premium Beans              406
Gourmet Beans              366
Espresso Beans             319
Herbal tea                 305
Black tea                  303
Drinking Chocolate         266
Clothing                   221
Organic Chocolate          221
House blend Beans          183
Green tea                  159
Green beans                134
Name: transaction_qty, dtype: int64

In [21]:
# Ver la lista completa ordenada de mayor a menor ingreso
#17
top_ingresos = df_new.groupby("product_type")["revenue"].sum().sort_values(ascending=False)
print(top_ingresos.head(1))

product_type
Barista Espresso    91406.2
Name: revenue, dtype: float64

In [22]:
# 18 que categoria aporta mas dinero?
top_ingresos_categoria = df_new.groupby("product_category")["revenue"].sum().sort_values(ascending=False)
top_ingresos_categoria.head(1)

product_category
Coffee    269952.45
Name: revenue, dtype: float64

In [23]:
# 19 tienda que genera mas ingresos
top_ingresos_tienda = df_new.groupby("store_location")["revenue"].sum().sort_values(ascending=False)
top_ingresos_tienda.head(1)

store_location
Hell's Kitchen    236511.17
Name: revenue, dtype: float64

In [24]:
df_new["store_location"].unique()

<ArrowStringArray>
['Lower Manhattan', 'Hell's Kitchen', 'Astoria']
Length: 3, dtype: str

In [25]:
df_new["transaction_date"]

0        2023-01-01
1        2023-01-01
2        2023-01-01
3        2023-01-01
4        2023-01-01
            ...
149111   2023-06-30
149112   2023-06-30
149113   2023-06-30
149114   2023-06-30
149115   2023-06-30
Name: transaction_date, Length: 149116, dtype: datetime64[us]

In [26]:
# 20 Día de la semana con mayores ingresos
df_new["day_of_week"] = df_new["transaction_date"].dt.day_name()
top_dias_ingresos = df_new.groupby("day_of_week")["revenue"].sum().sort_values(ascending=False)
top_dias_ingresos.head(1)

day_of_week
Monday    101677.28
Name: revenue, dtype: float64

In [27]:
# 21  a que hora se genera mas dinero
df_new["transaction_time"] = pd.to_datetime(df_new["transaction_time"], format="%H:%M:%S")
df_new["hour_of_day"] = df_new["transaction_time"].dt.hour

top_horas_ventas = df_new.groupby("hour_of_day")["revenue"].sum().sort_values(ascending=False)
top_horas_ventas.head(1)

hour_of_day
10    88673.39
Name: revenue, dtype: float64

In [28]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[us]
 2   transaction_time  149116 non-null  datetime64[us]
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
 11  revenue           149116 non-null  float64
 12  day_of_week       149116 non-null  str
 13  hour_of_day       149116 non-null  int32
dtypes: datetime64[us](2), float64(2), int32(1), int64(4), str(5)
memory usage: 23.6 MB

In [29]:
# 22 en promedio por transaccion cuanto se vende
df_new["transaction_qty"].mean()

np.float64(1.438276241315486)

In [30]:
# 23 ¿Cuánto dinero genera una transacción en promedio?
df_new["revenue"].mean()

np.float64(4.6863671906435265)

In [31]:
# 24 ¿Qué tienda vende más unidades?
ventas_tienda = df_new.groupby("store_location")["transaction_qty"].sum().sort_values(ascending=False)
ventas_tienda

store_location
Lower Manhattan    71742
Hell's Kitchen     71737
Astoria            70991
Name: transaction_qty, dtype: int64

In [32]:
# 24.1 ¿La tienda que más vende unidades también es la que más dinero genera?
info_tiendas = pd.DataFrame([ventas_tienda, top_ingresos_tienda])
info_tiendas

store_location   Lower Manhattan  Hell's Kitchen    Astoria
transaction_qty         71742.00        71737.00   70991.00
revenue                230057.25       236511.17  232243.91

In [33]:
#25 ¿Cuál es el unit_price promedio de cada product_category?
df_new.groupby("product_category")["unit_price"].mean().sort_values(ascending=False)

product_category
Coffee beans          21.018397
Branded               17.720214
Loose Tea              9.267438
Packaged Chocolate     9.050595
Drinking Chocolate     4.148827
Bakery                 3.551682
Coffee                 3.023646
Tea                    2.817121
Flavours               0.800000
Name: unit_price, dtype: float64

In [34]:
# 26. Los 10 productos que más ingresos generan
productos_mayor_ingreso= df_new.groupby("product_type")["revenue"].sum().sort_values(ascending=False).head(10)
productos_mayor_ingreso

product_type
Barista Espresso         91406.20
Brewed Chai tea          77081.95
Hot chocolate            72416.00
Gourmet brewed coffee    70034.60
Brewed Black tea         47932.00
Brewed herbal tea        47539.50
Premium brewed coffee    38781.15
Organic brewed coffee    37746.50
Scone                    36866.12
Drip coffee              31984.00
Name: revenue, dtype: float64

In [35]:
# 27. Producto más vendido vs. producto que más factura
top_vendidos= df_new.groupby('product_type')['transaction_qty'].sum().sort_values(ascending=False)
print("producto mas vendido".center(50, "-"))
print(top_vendidos.head(1))
print("producto que mas ingresos genera".center(50, "-"))
print(top_ingresos.head(1))
# top_ingresos = df_new.groupby("product_type")["revenue"].sum().sort_values(ascending=False)
top_vendidos_ingresos = pd.DataFrame([top_ingresos.head(10),top_vendidos.head(10)])
top_vendidos_ingresos.T

---------------producto mas vendido---------------
product_type
Brewed Chai tea    26250
Name: transaction_qty, dtype: int64
---------producto que mas ingresos genera---------
product_type
Barista Espresso    91406.2
Name: revenue, dtype: float64

                        revenue  transaction_qty
product_type
Barista Espresso       91406.20          24943.0
Brewed Chai tea        77081.95          26250.0
Hot chocolate          72416.00          17457.0
Gourmet brewed coffee  70034.60          25973.0
Brewed Black tea       47932.00          17462.0
Brewed herbal tea      47539.50          17328.0
Premium brewed coffee  38781.15          12431.0
Organic brewed coffee  37746.50          13012.0
Scone                  36866.12          10465.0
Drip coffee            31984.00          12891.0

In [36]:
productos_interes = ["Barista Espresso", "Brewed Chai tea"]
df_filtrado = df_new[df_new["product_type"].isin(productos_interes)][["product_type", "unit_price"]]
# 2. Agrupar por producto y calcular la media del precio
df_promedio = df_filtrado.groupby("product_type")["unit_price"].mean().reset_index()
df_promedio

       product_type  unit_price
0  Barista Espresso    3.655200
1   Brewed Chai tea    2.936993

¿Cuál vendió más unidades?
el producto que mas vendio unidades Brewed Chai tea con una cantidad de 26250 unidades
¿Cuál generó más ingresos?
el producto que mas genero ingresos fue Barista Espresso con una ganancia de 91406.2
¿Es el mismo producto?
no es el mismo producto
Si no lo es, ¿por qué crees que puede existir esa diferencia?
el Barista Espresso tiene un costo mayor y tuvo un gran flujo de ventas por eso genero mayor ingreso, pero el Brewed Chai tea tiene un promedio de precio unitario menor al Barista Espresso por lo tanto tiene una facil adquisicion en comparacion al Barista Espresso

recomendacion gpt: Insight: Barista Espresso generó más ingresos que Brewed Chai tea a pesar de vender menos unidades.

Explicación: Esto puede ocurrir porque el precio de venta unitario de Barista Espresso es superior. Por lo tanto, una menor cantidad de unidades puede generar mayores ingresos cuando el precio por unidad es suficientemente alto.
Y aquí aparece una fórmula que quiero que recuerdes:

Revenue = cantidad vendida × precio unitario

Eso explica perfectamente la diferencia.
Brewed Chai tea vendió más unidades, mientras que Barista Espresso generó más ingresos. Esto puede explicarse parcialmente por diferencias en el precio de venta unitario. Para comprobarlo, debemos comparar los precios promedio sin eliminar transacciones.

In [37]:
df_new.groupby("product_type")["unit_price"].mean().sort_values(ascending=False)

product_type
Premium Beans            34.028274
Clothing                 27.886878
Organic Beans            20.287952
Gourmet Beans            18.573770
House blend Beans        18.000000
Espresso Beans           17.430251
Housewares               13.448669
Drinking Chocolate       10.255789
Green beans              10.000000
Chai tea                  9.709368
Green tea                 9.250000
Black tea                 8.950000
Herbal tea                8.950000
Organic Chocolate         7.600000
Hot chocolate             4.148827
Pastry                    3.685979
Barista Espresso          3.655200
Scone                     3.534638
Biscotti                  3.419503
Premium brewed coffee     3.122452
Brewed Chai tea           2.936993
Organic brewed coffee     2.898021
Brewed herbal tea         2.744731
Brewed Black tea          2.744670
Brewed Green tea          2.742462
Gourmet brewed coffee     2.696641
Drip coffee               2.484959
Sugar free syrup          0.800000
Regular syrup             0.800000
Name: unit_price, dtype: float64

# 28. Evolución mensual de ingresos ¿Cómo evolucionan los ingresos de la cafetería a lo largo del período analizado?

In [141]:
df_new['anio_mes'] = df_new['transaction_date'].dt.to_period('M')
ingresos_por_mes = df_new.groupby('anio_mes')["revenue"].sum().reset_index()
ingresos_por_mes

  anio_mes    revenue
0  2023-01   81677.74
1  2023-02   76145.19
2  2023-03   98834.68
3  2023-04  118941.08
4  2023-05  156727.76
5  2023-06  166485.88

la evolucion mensual de los ingresos fue creciente a excepcon del segundo mes

# 29. ¿Qué mes tuvo más transacciones?, ¿El mes que genera más ingresos también es el mes con mayor cantidad de transacciones?

In [176]:
df_new.groupby('anio_mes')["transaction_id"].nunique().sort_values(ascending=False).head(1)

anio_mes
2023-06    35352
Freq: M, Name: transaction_id, dtype: int64

el mes que mas tuvo transacciones fue el sexto y el mes que mas ingresos hizo tambien es el de mayor transacciones

# 30 ¿Cuál es la hora de mayor actividad?, ¿A qué hora se realizan más transacciones?

In [177]:
print(df_new.groupby('hour_of_day')["transaction_id"].nunique().sort_values(ascending=False).reset_index().head(1))
print(top_horas_ventas.head(1))

   hour_of_day  transaction_id
0           10           18545
hour_of_day
10    88673.39
Name: revenue, dtype: float64

Las 10:00 es la hora con mayor número de transacciones registradas.

# 31. ¿El comportamiento horario es igual en todas las tiendas? Pregunta de negocio: ¿Todas las tiendas tienen el mismo horario de mayor actividad?

In [199]:
# df_new.groupby(['hour_of_day', 'store_location'])["transaction_qty"].sum().sort_values(ascending=False).head(1)
horario_mayor_actividad = (
    df_new.groupby(['store_location', 'hour_of_day'])['transaction_id']
    .nunique()
    .reset_index(name='transaction_count')
)
horario_mayor_actividad
horario_mayor_actividad.loc[
    horario_mayor_actividad.groupby('store_location')['transaction_count'].idxmax()
]
# horario_mayor_actividad.groupby(['store_location']).max().sort_values(ascending=False)
# df_new['store_location'].unique()

     store_location  hour_of_day  transaction_count
3           Astoria           10               5291
17   Hell's Kitchen           10               6957
32  Lower Manhattan           10               6297

Las 10:00 es la hora de mayor actividad en cada una de las tres tiendas.

# 32. ¿Qué categoría de productos genera más ingresos en cada tienda?

In [169]:
print(df_new.groupby(['store_location', 'product_category'])['revenue'].sum().sort_values(ascending=False))

store_location   product_category
Hell's Kitchen   Coffee                91222.65
Astoria          Coffee                89744.30
Lower Manhattan  Coffee                88985.50
Astoria          Tea                   67839.90
Hell's Kitchen   Tea                   64701.30
Lower Manhattan  Tea                   63864.75
                 Bakery                28328.94
Hell's Kitchen   Bakery                27386.95
Astoria          Bakery                26599.75
                 Drinking Chocolate    26335.25
Hell's Kitchen   Drinking Chocolate    23586.25
Lower Manhattan  Drinking Chocolate    22494.50
Hell's Kitchen   Coffee beans          18635.10
Lower Manhattan  Coffee beans          11230.95
Astoria          Coffee beans          10219.20
Lower Manhattan  Branded                6208.00
Astoria          Branded                5457.00
Hell's Kitchen   Loose Tea              4461.35
Lower Manhattan  Flavours               3767.20
                 Loose Tea              3558.25
Astoria          Loose Tea              3194.00
Hell's Kitchen   Flavours               2876.80
                 Branded                1942.00
Astoria          Flavours               1764.80
Hell's Kitchen   Packaged Chocolate     1698.77
Lower Manhattan  Packaged Chocolate     1619.16
Astoria          Packaged Chocolate     1089.71
Name: revenue, dtype: float64

la categoria de producto que mas genera por tienda es el coffee

In [171]:
df_new['transaction_id'].info()

<class 'pandas.Series'>
RangeIndex: 149116 entries, 0 to 149115
Series name: transaction_id
Non-Null Count   Dtype
--------------   -----
149116 non-null  int64
dtypes: int64(1)
memory usage: 1.1 MB